### ISSUE TITLE
readthedocs not updating

### ISSUE THREAD

**Issue by rbeyer** [planetarypy/pvl#39] opened 2020-03-03 17:46 UTC
As far as I understand how readthedocs works, it *should* be tracking the master branch of this repo, but the new documentation from the latest commits are not showing up there.  Anybody know why?

Maybe @wtolson or @godber (who are listed as the readthedocs Maintainers) need to flip a switch or something?  Not sure ...

**Comment by michaelaye** [comment] 2020-03-03 20:04
the issue is that it was set up using GitHub Services which are deprecated. We simply need to put a new hook in place. I'll see if I can do that.

**Comment by michaelaye** [comment] 2020-03-03 20:10
but also only @wtolson and @godber are maintainers on readthedocs, if that could be changed, it would be good. Will ping @godber on OpenPlanetary as well.

**Comment by godber** [comment] 2020-03-03 20:38
I have:

1. Managed to log into readthedocs
2. attempted to make @michaelaye a maintainer.

Please let me know if that worked or not.

**Comment by rbeyer** [comment] 2020-03-03 21:11
@godber Yes, that worked.  Michael fixed it up.  Now we're getting a docs build failure, but at least the process is working, so that's good.  Baby steps.

**Comment by michaelaye** [comment] 2020-03-03 21:11
i think that's all what was needed, thanks. Now we just need to tweak the recommended settings file until things compile, but I think we can close this issue. I also made Ross the maintainer, as he did all the work for the recent refactor.

**Closed by michaelaye** 2020-03-03 21:11 UTC
